### PR TITLE
Fix segfault when using unpickled STRtree in another process

### PR DESCRIPTION
**Pull request by kveretennicov**
GEOS STRtree handle was not excluded when pickling Python STRtree. When unpickled in another process it would become a dangling pointer and segfault.

### CODE REVIEW

**Comment by kveretennicov** [comment]
@sgillies would you prefer this to target `maint-1.7` instead of `master`?

**Comment by sgillies** [comment]
Yes, please @kveretennicov !

**Comment by kveretennicov** [comment]
Done, @sgillies :+1:

**Comment by sgillies** [comment]
Thanks very much @kveretennicov !

**Pull request merged**
