### PR TITLE
Fix doctests, run in CI

### LINKED ISSUE #992: CI: run doctests
Possible follow-up on https://github.com/Toblerity/Shapely/pull/979. With `pytest shapely --doctest-modules` we could actually run the doctests on CI (but that needs some fixes first, as there are some failures at the moment)

### PR DESCRIPTION
**Pull request by chadwhawkins**
Resolves #992.

### CODE REVIEW

**Comment by chadwhawkins** [comment]
After passing locally, some issues have arisen because of the various permutations run under CI. There are issues with the following:

- Speedups doctest fails based on flag (could just ignore this file)
- Floating points
- Dictionary ordering

To get these to pass consistently the succinctness of the examples would be lost. Running the doctests did identify a couple of mistakes in the examples. Maybe those changes should be kept and the CI automation dropped?

**Comment by jorisvandenbossche** [comment]
@chadwhawkins thanks for working on this!

If we run it on CI, we could maybe also limit it to a single build? (to not have to pass the tests in all possible setups)

**Comment by chadwhawkins** [comment]
@jorisvandenbossche I think that's a great suggestion. I've gone ahead and done that and have it configured to only run for Python 3.8 when both NumPy and speedsups are enabled.

**Review by mwtoews — APPROVED** [review]
Thanks, looks great!

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks @chadwhawkins !

**Pull request merged**
