### PR TITLE
Refactor __geo_interface__

### PR DESCRIPTION
**Pull request by bixb0012**
Between formatting discrepancies and problems with empty geometries, I decided to look holistically at how `__geo_interface__` was implemented.

The first thing I noticed is that `__geo_interface__` was implemented individually and independently within each geometry class instead of implementing within a base geometry class.  Another thing I noticed is the presence of `geometry.base.dump_coords()` that appears to go most of the way to dumping `__geo_interface__` coordinates.

 Since `dump_coords()` already exists and gets us most of the way to `__geo_interface__` coordinates, I decided to modify its code and consolidate `__geo_interface__` into a base geometry class.  *I couldn't determine what `dump_coords()` was being used for, so it may be the proposed changes break other code and should not be implemented.*

The proposed code results in the following results, which I believe are the desired results for `__geo_interface__`.
```python
>>> from shapely.wkt import loads
>>> 
>>> geoms = {
    'pt':   'POINT(10 10)',
    'ept':  'POINT EMPTY',
    'mpt':  'MULTIPOINT((15 15), (25 15))',
    'empt': 'MULTIPOINT EMPTY',
    'ln':   'LINESTRING(20 20, 30 30)',
    'eln':  'LINESTRING EMPTY',
    'mln':  'MULTILINESTRING((35 35, 45 45), (5 15, 15 25))',
    'emln': 'MULTILINESTRING EMPTY',
    'pg':  ('POLYGON((10 40, 30 40, 30 60, 10 60, 10 40), '
                      '(15 45, 15 55, 25 55, 25 45, 15 45))'),
    'epg':  'POLYGON EMPTY',
    'mpg': ('MULTIPOLYGON(((50 30, 70 30, 70 50, 50 50, 50 30), '
                            '(55 35, 55 45, 65 45, 65 35, 55 35)), '
                         '((40 10, 40 20, 50 20, 50 10, 40 10)))'),
    'empg': 'MULTIPOLYGON EMPTY',
    'gc':  ('GEOMETRYCOLLECTION(POINT(10 10), '
                               'POINT EMPTY, '
                               'LINESTRING(20 20, 30 30), '
                               'MULTILINESTRING EMPTY, '
                               'POLYGON((10 40, 30 40, 30 60, 10 60, 10 40), '
                                         '(15 45, 15 55, 25 55, 25 45, 15 45)))'),
    'egc':  'GEOMETRYCOLLECTION EMPTY'
}
>>> 
>>> for wkt in geoms.values():
...     geom = loads(wkt)
...     print "WKT: {}\n__geo_interface__: {}\n".format(wkt,
...                                                     geom.__geo_interface__)
...                                                     
WKT: MULTIPOLYGON(((50 30, 70 30, 70 50, 50 50, 50 30), (55 35, 55 45, 65 45, 65 35, 55 35)), ((40 10, 40 20, 50 20, 50 10, 40 10)))
__geo_interface__: {'type': 'MultiPolygon', 'coordinates': [(((50.0, 30.0), (70.0, 30.0), (70.0, 50.0), (50.0, 50.0), (50.0, 30.0)), ((55.0, 35.0), (55.0, 45.0), (65.0, 45.0), (65.0, 35.0), (55.0, 35.0))), (((40.0, 10.0), (40.0, 20.0), (50.0, 20.0), (50.0, 10.0), (40.0, 10.0)),)]}

WKT: MULTIPOLYGON EMPTY
__geo_interface__: {'type': 'MultiPolygon', 'coordinates': []}

WKT: MULTIPOINT((15 15), (25 15))
__geo_interface__: {'type': 'MultiPoint', 'coordinates': ((15.0, 15.0), (25.0, 15.0))}

WKT: MULTILINESTRING EMPTY
__geo_interface__: {'type': 'MultiLineString', 'coordinates': ()}

WKT: GEOMETRYCOLLECTION(POINT(10 10), POINT EMPTY, LINESTRING(20 20, 30 30), MULTILINESTRING EMPTY, POLYGON((10 40, 30 40, 30 60, 10 60, 10 40), (15 45, 15 55, 25 55, 25 45, 15 45)))
__geo_interface__: {'type': 'GeometryCollection', 'geometries': ({'type': 'Point', 'coordinates': (10.0, 10.0)}, {'type': 'Point', 'coordinates': ()}, {'type': 'LineString', 'coordinates': ((20.0, 20.0), (30.0, 30.0))}, {'type': 'MultiLineString', 'coordinates': ()}, {'type': 'Polygon', 'coordinates': ((10.0, 40.0), (30.0, 40.0), (30.0, 60.0), (10.0, 60.0), (10.0, 40.0))})}

WKT: LINESTRING EMPTY
__geo_interface__: {'type': 'LineString', 'coordinates': ()}

WKT: POINT(10 10)
__geo_interface__: {'type': 'Point', 'coordinates': (10.0, 10.0)}

WKT: LINESTRING(20 20, 30 30)
__geo_interface__: {'type': 'LineString', 'coordinates': ((20.0, 20.0), (30.0, 30.0))}

WKT: POINT EMPTY
__geo_interface__: {'type': 'Point', 'coordinates': ()}

WKT: MULTILINESTRING((35 35, 45 45), (5 15, 15 25))
__geo_interface__: {'type': 'MultiLineString', 'coordinates': (((35.0, 35.0), (45.0, 45.0)), ((5.0, 15.0), (15.0, 25.0)))}

WKT: MULTIPOINT EMPTY
__geo_interface__: {'type': 'MultiPoint', 'coordinates': ()}

WKT: POLYGON((10 40, 30 40, 30 60, 10 60, 10 40), (15 45, 15 55, 25 55, 25 45, 15 45))
__geo_interface__: {'type': 'Polygon', 'coordinates': ((10.0, 40.0), (30.0, 40.0), (30.0, 60.0), (10.0, 60.0), (10.0, 40.0))}

WKT: GEOMETRYCOLLECTION EMPTY
__geo_interface__: {'type': 'GeometryCollection', 'geometries': ()}

WKT: POLYGON EMPTY
__geo_interface__: {'type': 'Polygon', 'coordinates': ()}

>>> 
```

### CODE REVIEW

**Comment by sgillies** [comment]
@bixb0012 I appreciate the effort, but there are some spurious commits in this PR, the tests don't pass, and I'm not ready for a refactor of the __geo_interface__ code for 1.6. Let's consider this work for the *next* version of Shapely and I'll see about addressing Point and Polygon for 1.6 with the fewest code changes possible. Okay?

**Comment by bixb0012** [comment]
Sounds good.  I will take a look at why the tests failed.

I know this has been discussed in various places, but I see part of the `__geo_interface__` output challenge as being the desire to have all round brackets instead of allowing some square brackets.  I know `__geo_interface__` is GeoJSON-like and not strictly GeoJSON, but why deviate from the output format/appearance.  I understand the argument of geometry immutability and using tuples, but I see the practicality of being closer to GeoJSON appearance as having more value.  Just my two cents.

**Comment by bixb0012** [comment]
With the tests I have looked at that failed,  the tests were built around the old/existing `dump_coords()` outputting a mixture of lists and tuples.  If geometries, at least in shapely, are ostensibly immutable, should `dump_coords()` be outputting lists and tuples or just tuples?

I don't think this is an issue with the code as much as the tests not being updated to reflect a change to `dump_coords()` that is more consistent with an all-tuple output for coordinate dumps.

**Comment by bixb0012** [comment]
Although the code I modified for `dump_coords()` handled empty geometries, it turns out it didn't handle correctly multipart geometries with a single part, so it will need to be updated.

**Pull request closed without merging**
