### PR TITLE
Maint 1.7: backport linux builds to Github Actions

### LINKED ISSUE #1079: Test failure with geos 3.9.0
## Expected behavior and actual behavior.

The test `SvgTestCase.test_collection` fails for Shapely 1.7.1 with geos 3.9.0. 

```
======================================================================
FAIL: test_collection (tests.test_svg.SvgTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/package/community/py3-shapely/src/Shapely-1.7.1/tests/test_svg.py", line 176, in test_collection
    self.assertSVG(
  File "/home/builder/package/community/py3-shapely/src/Shapely-1.7.1/tests/test_svg.py", line 41, in assertSVG
    self.assertEqual(svg_elem, expected)
AssertionError: '<g><polyline fill="none" stroke="#66cc99" str[158 chars]</g>' != '<g><circle cx="7.0" cy="3.0" r="3.0" stroke="[158 chars]</g>'
- <g><polyline fill="none" stroke="#66cc99" stroke-width="2.0" points="4.0,2.0 8.0,4.0" opacity="0.8" /><circle cx="7.0" cy="3.0" r="3.0" stroke="#555555" stroke-width="1.0" fill="#66cc99" opacity="0.6" /></g>
+ <g><circle cx="7.0" cy="3.0" r="3.0" stroke="#555555" stroke-width="1.0" fill="#66cc99" opacity="0.6" /><polyline fill="none" stroke="#66cc99" stroke-width="2.0" points="4.0,2.0 8.0,4.0" opacity="0.8" /></g>
```

So just the order of the polyline and the circle in the SVG changed.

## Steps to reproduce the problem.

Use `python3 setup.py build`

## Operating system

Alpine Linux Edge

## Shapely version and provenance

Shapely 1.7.1

### PR DESCRIPTION
**Pull request by mwtoews**
This is a backport of #1076 and #1078 to the `maint-1.7` branch.

Also, fix failing test from GEOS 3.9.0; properly closes #1079

### CODE REVIEW

**Comment by mwtoews** [comment]
I'm not sure if there is any appetite for a 1.7.2 maintenance release (that has clean tests with current GEOS 3.9.0), but here it is anyways.

I think there is much more appetite for a 1.8.0 release (#1066)

**Comment by sgillies** [comment]
Thank you for this @mwtoews ! I'm trying to decide whether it's worth our time to make a 1.7.2 with GEOS 3.9.1. That version of GEOS does fix a bug the project considers rather critical.

**Comment by jorisvandenbossche** [comment]
I *think* that mentioned fix is for a regression in GEOS 3.9.0. So doing a 1.7.2 release (for that reason) is only relevant if Shapely 1.7.1 would already be packages with GEOS 3.9.0, which is not the case I think?

**Comment by sgillies** [comment]
@jorisvandenbossche i just revisited the shapely-wheels repo in the mapbox org (where I moved it so my employer can pay for wheel builds) and indeed, we are still at 3.8.0 there.

**Comment by mwtoews** [comment]
@jorisvandenbossche that's correct for the binary wheels via pip, which is currently shapely 1.7.1 with geos 3.8.1 (I think).

The only shapely users impacted by the geos 3.9.0 bug were using conda-forge.

One reason to consider a maintenance release with geos 3.9.1 is potential performance improvements with OverlayNG operators.

**Comment by jorisvandenbossche** [comment]
> The only shapely users impacted by the geos 3.9.0 bug were using conda-forge.

And those are already updated to 3.9.1

> One reason to consider a maintenance release with geos 3.9.1 is potential performance improvements with OverlayNG operators.

Yes, certainly, that's a good reason I think to upload new packages. It's really an impressive improvement sometimes.

**Pull request merged**
