### PR TITLE
Let user set colors for GeometryCollection elements in Jupyter Notebook

### PR DESCRIPTION
**Pull request by invisibleroads**
```
from shapely.geometry import GeometryCollection, Point

GeometryCollection([
    Point(0, 0),
    Point(1, 1),
], colors=['red', 'blue'])
```

### CODE REVIEW

**Comment by invisibleroads** [comment]
@minrk

**Comment by sgillies** [comment]
@invisibleroads this is a neat idea, but I can't support adding a colors attribute to geometries. I've been saying "no" to proposals for an srid attribute for a long time, so it's not that I'm specifically against colors. I don't want to complicate the classes more than they already are or encumber them with new visualization features and responsibilities.

**Comment by invisibleroads** [comment]
Heh that's true, if you accept this pull request then you might get inundated by feature requests for customized visualization which will complicate the original scope of shapely as an optimized GEOS wrapper.

I moved the class to a [separate package](https://github.com/invisibleroads/geotable/blob/master/geotable/__init__.py) and renamed the class to ColorfulGeometryCollection.

Thank you very much for your work on shapely and other spatial packages. We use it extensively in our [algorithms for planning off-grid electricity infrastructure](https://crosscompute.com/n/JrbhgevrX9nf2wr2tF7iZZdQfJr7I8A0/_/Logs/Assemble%20Algorithm%20(1st%20Implementation)%2020171115).

https://crosscompute.com/n/JrbhgevrX9nf2wr2tF7iZZdQfJr7I8A0

**Comment by sgillies** [comment]
@invisibleroads thanks for understanding! That looks like a good approach to me.

**Pull request closed without merging**
