### PR TITLE
Fix invalid scape sequence warning

### PR DESCRIPTION
**Pull request by zetaatlyft**
Made changes in Docstrings to avoid "invalid escape sequence" DeprecationWarnings with Python 3.6

### CODE REVIEW

**Comment by mwtoews** [comment]
This could be easier fixed by declaring the docstrings as literal strings, by prefixing with an `r`:
```python
def foo():
    r"""Foo

    \whatever
    """
    pass
````

**Comment by zetaatlyft** [comment]
> This could be easier fixed by declaring the docstrings as literal strings, by prefixing with an `r`:
> 
> ```python
> def foo():
>     r"""Foo
> 
>     \whatever
>     """
>     pass
> ```

thank you for the comment @mwtoews. I added the suggestion.

**Comment by sgillies** [comment]
Are the backticks in the docstrings the root problem? I'd be willing to remove them. Putting extra modifiers on the docstrings seems a little odd, but if I saw some prior art I would happily concede.

**Comment by jorisvandenbossche** [comment]
> Are the backticks in the docstrings the root problem?

Yes, I suppose so. In pandas we eg have some docstrings with a latex equation, and then we also use the "raw" string to deal with this.

**Pull request merged**
