### PR TITLE
Improving affine_transform functions from issue #439

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
Created the affine_matrix_builder class in affinity.py to allow affine matrices to be combined.
Affine transforms can now be applied with `geom_transformed = affine_matrix_builder(Point(1,1)).rotate(90,(0,0)).translate(20, 30).transform()`
It also automatically determines when to combine the affine matrices or when to apply the last transform and store the current transform.

Tests for the class have been added in test_affinity.py 

Documentation has been updated for the class in manual.rst

Runtime of some affine transforms has decreased by 30%

### CODE REVIEW

**Comment by BebeSparkelSparkel** [comment]
@snorfalorpagus 
I needed to include numpy in affinity.py but I'm not sure were to add numpy in setup.py

**Comment by BebeSparkelSparkel** [comment]
@coveralls I'm looking at the [continuous integration error report of the failed 3.5 logs lines 365-367](https://travis-ci.org/Toblerity/Shapely/jobs/181421038) and the code shown in the log does not match the current commit version of the file. Is there a way to check and make sure it is using the latest commit.

**Comment by snorfalorpagus** [comment]
I'm certainly no expect with this. Could you explain why some transformations can't be combined? I'm referring to this comment:

> Holds the safe relationships of when two affine matricies can be combined.

**Comment by BebeSparkelSparkel** [comment]
If a rotation then a translation is applied then the affine matrices can be combined and will create the same result as when a rotation and then a translation is applied to the object. However, if a translation then a rotation is applied then the combined affine matrices will have a different result than if if the translation and rotation affine matrices are applied separately. Here's an example where the order of the transformation matters.
```python
>>> from shapely.geometry import Point
>>> from shapely.affinity import rotate, translate
>>> 
>>> print(
...   translate(
...     geom=rotate(
...       geom=Point(1,1),
...       angle=90,
...       origin=(0,0)
...     ),
...     xoff=1,
...     yoff=1
...   )
... )
POINT (0 2)
>>> 
>>> print(
...   rotate(
...     geom=translate(
...       geom=Point(1,1),
...       xoff=1,
...       yoff=1
...     ),
...     angle=90,
...     origin=(0,0)
...   )
... )
POINT (-2 2)
>>> 
```
If the order isn't preserved and the affine matrices are always combined the result will always be the case where the rotate then the translate is applied, Point (0 2). Meaning if using the combine matrices method it would be impossible to translate then rotate a geometric object. So, users would have to consider what cases they could combine the matrices and when they would have to apply the matrices separately.
There are some more specific cases where the matrices can be combined like when the some transforms have the same origin, but I haven't investigated those cases enough to have added them to the affine_matrix_builder._combine_matrices method.

**Comment by BebeSparkelSparkel** [comment]
@snorfalorpagus 
Does that make sense or do you have a way to preserve the transformation order when combining the affine matrices?

**Comment by BebeSparkelSparkel** [comment]
Do you plan on pulling this?

**Comment by sgillies** [comment]
@BebeSparkelSparkel I haven't been able to make the time for the review this deserves, but soon, I promise!

**Comment by BebeSparkelSparkel** [comment]
Ok thanks!

**Comment by sgillies** [comment]
@snorfalorpagus @mwtoews I'd be super grateful 🙏 if either of you could join me in reviewing this. I think it's good and mainly needs some test restructuring, but I may have overlooked something.

**Pull request closed without merging**
