### PR TITLE
Deprecate setting of custom attributes on geometry objects

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/Toblerity/Shapely/pull/1181 (and https://github.com/Toblerity/Shapely/pull/1180/files#r693378882). _If_ we want to disallow it for Shapely 2.0, this is adding a deprecation warning for it for 1.8

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@sgillies @mwtoews you're fine with this additional deprecation?

**Review by mwtoews — APPROVED** [review]
Changes look good for shapely 1.8.

**Comment by mwtoews** [comment]
The only thing we can't warn against is users that extend geometry types:
```python
from shapely.geometry import Point

class MyPoint(Point):
    extra = 123

mp = MyPoint(2, 4)
print(mp.extra)  # 123
mp.extra = 456
print(mp.extra)  # 456
```

**Comment by jorisvandenbossche** [comment]
I suppose that in _theory_ we could also add a warning when subclassing the geometry classes (with a metaclass, see eg https://stackoverflow.com/questions/16056574/how-does-python-prevent-a-class-from-being-subclassed), but not directly sure how that impacts other things.

**Comment by jorisvandenbossche** [comment]
I am going to interpret the thumbs up of @sgillies at https://github.com/Toblerity/Shapely/pull/1181 as an approval of the general idea, and merge this.

**Pull request merged**
