### PR TITLE
Merge shapely-2.0 branch into main

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/Toblerity/Shapely/issues/962#issuecomment-767440130

This contains all changes that were made up to now for the shapely-2.0 branch. Now we have branched for maint-1.8, I think it would be a good time to move the shapely-2.0 change into master. 
I would propose to merge this PR with the "Rebase and merge" strategy to preserve the commits here (directly mapping to one of the PRs). Another option is to rename the shapely-2.0 branch to master, but doing it through this PR seems more transparent.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@sgillies are you OK with going forward here? This is all content from previous PRs (but so essentially moving the shapely-2.0 branch to as the main branch)

**Comment by sgillies** [comment]
@jorisvandenbossche let's do it!

**Comment by jorisvandenbossche** [comment]
OK, done :) 
I will rebase some of the open PRs that were on top of this branch against the main branch then.

**Comment by jorisvandenbossche** [comment]
(actually, I already did my other PRs (https://github.com/Toblerity/Shapely/pull/1222, https://github.com/Toblerity/Shapely/pull/1219) agaisnt `main`)

**Pull request merged**
