### PR TITLE
Build docs on Read the Docs

### LINKED ISSUE #337: Automatic doc builds
Automate our doc build and publication workflow using Travis's deploy system. 

See also #336.

### PR DESCRIPTION
**Pull request by Juanlu001**
In the same spirit as https://github.com/Toblerity/Fiona/pull/466 and encouraged by the discussion on https://github.com/Toblerity/Fiona/issues/258, I made a similar pull request to build Shapely docs on Read the Docs. You can see the result here:

http://juanlu001-shapely.readthedocs.io/en/latest/

Closes #337.

### CODE REVIEW

**Comment by sgillies** [comment]
🙏 @Juanlu001, I've ported this to maint-1.6 et voilà: https://shapely.readthedocs.io/en/latest/.

**Comment by Juanlu001** [comment]
Awesome! :) Thanks!

**Comment by Juanlu001** [comment]
I've noticed that many places still point to http://toblerity.org/shapely/. Are you planning to do a redirect from there? Or may I change the links to http://shapely.readthedocs.io/en/stable/?

**Comment by sgillies** [comment]
@Juanlu001 would you be willing to change them to relative links when possible?

**Comment by Juanlu001** [comment]
I don't know what I was thinking but you changed the docs URL two days earlier https://github.com/Toblerity/Shapely/commit/b1e1bd361dcbf092b74806cd7bab5e660d092220 perhaps I was looking at the wrong place. No further action needed :)

**Pull request merged**
