### PR TITLE
Corrected restype on GEOSPrepared functions (c_int -> c_byte)

### PR DESCRIPTION
**Pull request by snorfalorpagus**
This fixes a bug with prepared geometries highlighted in issue #268. The `restype` was incorrectly set to `c_int` rather than `c_byte`. This caused unexpected results on Windows only, although I'm not sure why.

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
There are a few more issues I think should be addressed before this is merged:

* Predicate methods on prepared geometries are missing docstrings.
* `errcheck_predicate` should be used for prepared geometries as it is for regular geometries, but isn't currently.
* Not all predicates are implemented (e.g. `covers` is implemented for prepared geometries but not regular geometries, whereas `touches` is implemented for regular geometries but not prepared geometries).

**Comment by snorfalorpagus** [comment]
I think that's everything. Ready for review.

**Comment by sgillies** [comment]
@snorfalorpagus Thanks!

**Comment by bixb0012** [comment]
@snorfalorpagus, thanks from me as well.  I look forward to working with these changes.

**Pull request merged**
