### PR TITLE
Revise AppVeyor setup for Windows

### PR DESCRIPTION
**Pull request by mwtoews**
* Build GEOS version 3.8.0 using CMake/Ninja/Visual C++
* Build wheels for 8 combinations of x86/x64 and Py35/Py36/Py37/Py38
* Don't build wheels for Py27, as it's too difficult and a low priority
* Remove unused scripts from previous setup

The aim of this workflow is to allow Windows users to use `pip install shapely`; see #367

### CODE REVIEW

**Comment by sgillies** [comment]
This looks good to me, I lack the Windows and AppVeyor expertise that might be needed to see any problems. For my part: I'll work on setting up AppVeyor support for this repo.

Related: I recently acquired the https://github.com/shapely organization and am curious to know what you'd like about moving the repo there. Toblerity is pretty obscure and shapely seems like a more normal organization name for the project and its related projects.

**Comment by mwtoews** [comment]
@sgillies when an AppVeyor account is created and linked to this repo, I'll add another commit to add a build status badge to README.rst and also trigger the first build.

As for potential repo move, it's your call, but I don't see any issues with it. Two things to double-check if links get redirected (e.g. would  `https://github.com/Toblerity/Shapely/pull/819` navigate to `https://github.com/shapely/shapely/pull/819`?). The second check is to ensure the issue and PR numbers are not reset to 1. My hunch is that neither of these are issues if you transfer an existing repo. Also, would Fiona and rtree follow along to the new organization name?

I'd also suggest renaming this repo name from titlecase "Shapely" to lowercase "shapely". In a possibly related curiosity, [Fiona](https://github.com/Toblerity/Fiona) and [rtree](https://github.com/Toblerity/rtree) shows how many other projects depend on them with a "Used by" button at the top of the main repo website. Why does Shapely not show this?

**Comment by sgillies** [comment]
@mwtoews I created a new "frs-ci" account on AppVeyor, made each of us members of the team with admin role, and created a new project: https://ci.appveyor.com/project/frsci/shapely.

As to the GitHub "used by" button, my understanding is that it may (or may not?) appear at some future time. It seems to be a slow rollout.

**Comment by mwtoews** [comment]
This PR is now ready to be merged. Full build takes about 1 hour, but the GEOS builds are cached, so subsequent builds shouldn't take too long (~1 min x 8 in current matrix).

**Pull request merged**
