### PR TITLE
Interpolate section

### PR DESCRIPTION
**Pull request by ewsterrenburg**
Added a section operation (https://github.com/Toblerity/Shapely/issues/456) for review.

### CODE REVIEW

**Comment by ewsterrenburg** [comment]
@sgillies
Questions from my side...

- What's your opinion on naming (I'd prefer "segment", yet I see that is already being used for the part of a line between two vertices), location and code?

- Except for the docstrings, in which places should the functionality be documented?

- Am I overlooking something fundamental...

**Comment by sgillies** [comment]
@ewsterrenburg the code looks good to me and I appreciate that it's completely covered by the tests.

Documentation: can you add a paragraph to the https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst#other-operations section of the manual?

Naming: what would you think about `slice()`?

**Comment by ewsterrenburg** [comment]
@sgillies 
Good to hear :)

Will add a paragraph as specified.

Regarding to names, I actually considered `slice()`, yet chose `section()` since I strongly associate slice with lists/discrete collections. None-the-less, `section()` doesn't make me very happy either, so I could change it to `slice()` if you prefer.

**Comment by sgillies** [comment]
How about `substring()` as in PostGIS? http://postgis.net/docs/manual-2.0/ST_Line_Substring.html

**Comment by ewsterrenburg** [comment]
I like it, `substring()` it is.

**Comment by sgillies** [comment]
@ewsterrenburg okay with you if I change the base of the PR from 'master' to 'main-1.6' so we can have this feature in 1.6.0?

**Comment by ewsterrenburg** [comment]
Sure.

**Comment by sgillies** [comment]
@ewsterrenburg can you please try to rebase this on the maint-1.6 branch? It's all my fault because I branched too early, really, and if you don't have time I will do it myself tomorrow or Friday.

**Comment by ewsterrenburg** [comment]
Hi @sgillies 

Sorry, I had some guests over and was away from keyboard for some days... If it's still relevant, I can look into this (however I do not fully understand what you expect...)

**Comment by sgillies** [comment]
I'm going to merge to master and not into the 1.6.x branch, it's a little late for that.

**Pull request merged**
